services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_URL= Your Databse URL
      - TOKEN_KEY= YOUR SECRET KEY
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

